version: "2"
services:
  webserver:
    image: nginx:alpine
    networks:
      - default
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
