<?php

require_once '../credentials.php';

// Aplicarea unui discount
$estimate = array(
    'companyVatCode'        => $companyVatCode,
    'client'                => array(
        'name'      => "Intelligent IT",
        'vatCode'   => "RO12345678",
        'address'   => "str. Sperantei, nr. 5",
        'regCom'    => "",
        'city'      => "Sibiu",
        'county'    => "Sibiu",
        'country'   => "Romania",
        'email'     => "office@smartbill.ro",
    ),
    'issueDate'             => date('Y-m-d'),
    'seriesName'            => $companyProformaSeries,
    'dueDate'               => date('Y-m-d', time() + 14*3600),
    'deliveryDate'          => date('Y-m-d', time() + 1*3600),
    'products'              => array(
        array(
            'name'                      => "Mapa A4",
            'code'                      => "ccd1",
            'translatedName'            => "",
            'translatedMeasuringUnit'   => "",
            'isDiscount'                => false,
            'measuringUnitName'         => "buc",
            'currency'                  => "RON",
            'quantity'                  => 2,
            'price'                     => 40,
            'isTaxIncluded'             => true,
            'taxName'                   => "Normala",
            'taxPercentage'             => 20,
            'saveToDb'                  => false,
            'warehouseName'             => "",
            'isService'                 => false,
        ),
        array(
            'name'                      => "Biblioraft Plastifiat",
            'code'                      => "ccd2",
            'translatedName'            => "",
            'translatedMeasuringUnit'   => "",
            'isDiscount'                => false,
            'measuringUnitName'         => "buc",
            'currency'                  => "RON",
            'quantity'                  => 3,
            'price'                     => 60,
            'isTaxIncluded'             => true,
            'taxName'                   => "Normala",
            'taxPercentage'             => 20,
            'saveToDb'                  => false,
            'warehouseName'             => "",
            'isService'                 => false,
        ),
        array(
            'name'                      => "Discount valoric pe produsul 2",
            'translatedName'            => "",
            'translatedMeasuringUnit'   => "",
            'isDiscount'                => true,
            'numberOfItems'             => 1,
            'measuringUnitName'         => "buc",
            'currency'                  => "RON",
            'quantity'                  => 1,
            'isTaxIncluded'             => true,
            'taxName'                   => "Normala",
            'taxPercentage'             => 20,
            'discountType'              => SmartBillCloudRestClient::DiscountType_Valoric,
            'discountPercentage'        => 0,
            'discountValue'             => -15,
        ),
        array(
            'name'                      => "Discount procentual pe produsul 1 si 2",
            'translatedName'            => "",
            'translatedMeasuringUnit'   => "",
            'isDiscount'                => true,
            'numberOfItems'             => 2,
            'measuringUnitName'         => "buc",
            'currency'                  => "RON",
            'quantity'                  => 1,
            'isTaxIncluded'             => true,
            'taxName'                   => "Normala",
            'taxPercentage'             => 20,
            'discountType'              => SmartBillCloudRestClient::DiscountType_Procentual,
            'discountPercentage'        => 10,
            'discountValue'             => 0,
        ),
    ),
);
echo 'Aplicarea unui discount: ';
try {
   $output = $sbcClient->createProforma($estimate); //estimate.Number will be  generated by the server
   $estimateNumber = $output['number'];
   $estimateSeries = $output['series'];
   echo $estimateSeries . $estimateNumber . "  ";
} catch (Exception $ex) {
    echo $ex->getMessage();
}