<?php

require_once '../credentials.php';

// Firma neplatitoare de TVA
$invoice = array(
    'companyVatCode'    => $companyVatCode,
    'client'            => array(
        'name'      => "intelligent IT",
        'vatCode'   => "RO12345678",
        'address'   => "str. Sperantei, nr. 5",
        'city'      => "Sibiu",
        'country'   => "Romania",
    ),
    'isDraft'           => false,
    'issueDate'         => date('Y-m-d'),
    'seriesName'        => $companyInvoiceSeries,
    'dueDate'           => date('Y-m-d', time() + 14*3600),
    'deliveryDate'      => date('Y-m-d', time() + 1*3600),
    'products'          => array(
        array(
            'name'              => "Produs 1",
            'code'              => "ccd1",
            'isDiscount'        => false,
            'measuringUnitName' => "buc",
            'currency'          => "RON",
            'quantity'          => 2,
            'price'             => 10,
            'isService'         => false,
        )
    )
);
echo 'Firma neplatitoare de TVA: ';
try {
    $output = $sbcClient->createInvoice($invoice); //invoice.Number will be  generated by the server
    $invoiceNumber = $output['number'];
    $invoiceSeries = $output['series'];
    echo $invoiceSeries . $invoiceNumber;
} catch (Exception $ex) {
    echo $ex->getMessage();
}